### ISSUE TITLE
Line endings in dist/cli.js prevent shebang from working in zsh

### ISSUE THREAD

**Issue by mvasilkov** [joshuatz/git-date-extractor#12]
Hi,

In dist/cli.js (the one uploaded to npm, anyway) line endings seem to be CRLF. This breaks the `#!` line in zsh:

```
$ git-dates --onlyIn content --outputToFile true --outputFileName generated/git-dates.json
env: node\r: No such file or directory
error Command failed with exit code 127.
```

Looks that it's the same issue as e.g. https://github.com/jwbay/i18next-json-sync/issues/7

Anyway, thanks for the useful script!

**Comment by joshuatz** [comment]
@mvasilkov  Thanks for catching this and the extra details you provided - much appreciated! This does appear to be an identical issue - my `src` files are all `lf` (I even have an IDE config to force it), but apparently TSC defaults to OS instead of preserving source file formatting.

I've adjusted my repo and pushed a new version (`v4.0.1`) - please let me know if this does not fix things for you.
